services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      - DB_URL=postgres://admin:password@postgres-db:5432/merch_store-db
      - JWT_SECRET=too_elaborate_jwt_secret
      - PORT=8080
    ports:
      - "8080:8080"
    networks:
      - app_network

  postgres-db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: merch_store-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 10s
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
